### ISSUE TITLE
추가 컴포넌트 정리

### ISSUE THREAD

**Issue by billy5982** [Quick-Project/GoodFe#14]
- [ ] 추가 컴포넌트 파악 및 정리 댓글에 추가 해놓을게요

**Comment by billy5982** [comment]
현재 파악
Code Push button click, Theme 컴포넌트화, 결과창에 광고 창

**Comment by haileyport** [comment]
월요일 회의 아젠다 2-1 종료 후에 정리해서 한번 더 올려주세용~

**Comment by billy5982** [comment]
모달 컴포넌트화 로직 구상 필요
