### ISSUE TITLE
MAEK JOO IDE 파악

### ISSUE THREAD

**Issue by 94sssh** [Quick-Project/GoodFe#16]
MAEK JOO IDE

Main
- [ ] 상단 로고의 화살표 누를시 칵테일 주소로 이동
- [ ] 소스 코드 공개 라디오 버튼

인풋 창
- [ ] 이름 입력 창
- [ ] 제목 입력 창
- [ ] 내용 입력 창

입력 창
- [ ] 테마 변경 버튼 클릭 -> 테마 변경
- [ ] 제출 버튼 클릭 -> 모달 창 등장

모달 창
1. 140자 이하
    - [ ] 편지 전송 및 ‘제출이 완료되었습니다’ 모달에 버튼 2개 (메인 화면 가기, 결과 창 가기)
    - [ ] 1.1 메인 화면 가기 클릭 -> 메인 창으로 이동
    - [ ] 1.2 결과 창 가기 클릭 -> 결과 창으로 이동
2. 140자 초과
    - [ ] ‘글자 수를 줄여주세요’ 모달에 버튼 2개 (힌트보기 버튼, 글자 수 수정 버튼)
    - [ ] 2.1 힌트보기 버튼에 호버시  ‘길이보단 진심이 중요…’로 텍스트 변경
    - [ ] 2.2 글자 수 수정 버튼 클릭하면 편지 쓰기로 돌아가기

- [ ] 공통 컴포넌트 - 제출 버튼, 테마 변경 버튼

**Comment by billy5982** [comment]
아이고 정리해주셔서 가아아아암사 합니다 ㅎㅎ 앤디가 한꺼번에 정리해줘서 이슈 닫을게요~~~
