### ISSUE TITLE
Progamers IDE 분석

### ISSUE THREAD

**Issue by heoputer** [Quick-Project/GoodFe#20]
### 컴포넌트

- [ ] 문제 설명 컴포넌트
- [ ] 입력창 컴포넌트
- [ ] 실행 결과 컴포넌트
- [ ] 웹 브라우저 헤더 (ex 북마크, 탭) // 맥주 페이지랑 공유 가능할듯.
- [ ] 프로게이머스 헤더 ![image](https://user-images.githubusercontent.com/58350169/197343624-28a143b0-028c-4d1d-8da2-b99a353cb2c8.png)

### 밑으론 전반적으로 공유 될 수 있는 내용들

- [ ] 인풋 컴포넌트 // 받는사람, 제목, 내용 등 재사용 가능하게
- [ ] 제출 버튼 
- [ ] 테마 변경 버튼
- [ ] 제출 버튼 로직 구현
- [ ] 글자수 체크 로직 구현

일단 생각나는 것은 여기까지 적어보았는데 더 추가할 내용, 궁금한 내용있으면 댓글 혹은 DM 주세용~~

**Comment by billy5982** [comment]
감사합니다!! 고생많으셨어요!! 앤디가 3사 통합에 정리해줘서 이슈 닫을게요~~
