### ISSUE TITLE
VS CodeStates IDE 파악

### ISSUE THREAD

**Issue by nada1221** [Quick-Project/GoodFe#8]
VSC IDE

Main 
- [ ] 편지 쓰기 클릭 시 vsc code 입력 창으로 전환(분기)
- [ ] 최근항목 -> 각자 멘트 클릭시 개개인의 깃허브 창 띄우기(새 창으로)
- [ ] checkBox 클릭 시 프로젝트 깃허브 창 띄우기 -> alert 스타는 누르셨나요?

입력 창
/* (왼 쪽 폴더& 파일 창은 이미지 파일로 대체해도 괜찮겠다고 생각합니다. 
굳이 저기를 유저가 건드릴 필요도 없고…) 왼쪽에 파일 && 돋보기 제외하고 싸그리 다 지울 생각입니다.) */ -- 동의보감

- [ ] Theme Change button click (순서를 정해서 vsCode -> proGamers -> Maekjoo -> vsCode 순서로 분기.)
- [ ] Code Push button click 
	5-1. 140자 이하 -> 정상적으로 git add . 발현(생성)
	5-2. 140자 초과 -> error text 생성 후 글자 수 정정 요청 (생성) && codePush button 재활성화 (생성)
- [ ]  정상 전송 후 -> 검색 창으로 가시겠습니까? 발현(생성)
 	6-1. Y === 검색 창으로 분기(이동)
	6-2. N === 메인 창으로 분기(이동)

공통 컴포넌트 예상
- [ ] Code push && theme change button 
- [x] 밖에 없어 보입니다.

**Comment by billy5982** [comment]
확인 완료! Theme 버튼은 컴포넌트화 해서 컴포넌트 내부에서 처리하는 것도 좋을 거 같네요 이 부분은 제가 조금 정리해서 나중에 공지할게용~~
고생 많으셨습니다~

**Comment by haileyport** [comment]
개발할 컴포넌트로 나눠서 내일 회의 시간에 브리핑해주시면 더더 좋을 거 같아요 😉
브리핑 끝나고 백준 코멘트 이후에 저희 만나서 봅시당 기능정리 감사해요~~

**Comment by billy5982** [comment]
같이 확인 완료했으니깐 클로즈 할게요~!
