### ISSUE TITLE
DB 세팅

### ISSUE THREAD

**Issue by haileyport** [Quick-Project/GoodFe#9]
월요일까지 할 일입니다 컨펌 부탁드려용 파트장님~

- [x] planetScale 서버 생성
- [x] prisma 설치
- [x] prisma + planetScale 연결
- [x] DB schema 세팅
- [x] 편지 TB 테스트 더미데이터 생성

**Comment by haileyport** [comment]
실제 DB에 들어갈 내용입니다

- [ ] FE40 User Table Data init
- [ ] 검색결과 Random Ment Table Data init 
  - 받는 사람 안 보여주는 이유 넣는 테이블

**Comment by haileyport** [comment]
DB세팅 중 이슈

PlanetScale이 1인 1개까지 무료입니다.
제가 다른 프젝때 썼더니ㅎㅎ... 혹시 계정지원 가능한가요 피터 @jaehongg 
오늘 자리비움이시니 천천히 답장주십숑

**Comment by haileyport** [comment]
피터가 해결해줬습니다~~ 굿

> DB세팅 중 이슈
> 
> PlanetScale이 1인 1개까지 무료입니다. 제가 다른 프젝때 썼더니ㅎㅎ... 혹시 계정지원 가능한가요 피터 @jaehongg 오늘 자리비움이시니 천천히 답장주십숑

**Comment by 94sssh** [comment]
FE40 User Table Data init 작업 완료했습니다! 확인 부탁드려요~ @haileyport

**Comment by haileyport** [comment]
> FE40 User Table Data init 작업 완료했습니다! 확인 부탁드려요~ @haileyport

정말 미안해요... 스키마 바꾸다가 그만... 다시 확인 부탁드립니다...
